### ISSUE TITLE
Reparat Layout stricat

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#1]
Am vazut ca ai copiat designul de la calulatoru din windows. Arata bine! 

Dar ca si idee, **orice interfata nu ar trebui sa aiba spatii goale prea multe**. In cazul tau, e foarte mult: 
![image](https://user-images.githubusercontent.com/6756850/130403234-bd36e176-1f71-458e-8b41-a6cb2dd884d4.png)

Ai 2 optiuni: 
1. Sa faci butoanele sa se faca mai mari, sa ocupe tot spatiu disponibil (ca la win calculator): 
![image](https://user-images.githubusercontent.com/6756850/130403356-044c1225-6c4e-4a06-b750-0e1c1871e5a7.png)

Pt asta ai nevoie sa folosesti layout panels, si sa pui butoanele sa faca styretch, dar nu recomand sa faci asta, ca in windows forms e mai complicat si inveti aproape degeaba (eventual poti incerca in WPF, care e un fel de winforms). 

2. **[Recomandat]** Sa nu mai lasi aplicatia sa faca resize (sa ramana mereu mica). Pt asta ai nevoie sa schimbi properietatile de FormBorderStyle (sa nu mai faca resize cu mouse-ul), si MaximizeBox (sa nu mai apara butonul de maximizat fereastra). 

![image](https://user-images.githubusercontent.com/6756850/130404263-f3356454-8204-4724-944c-ee1417a52165.png)

**Comment by Dorin-Foaltin** [comment]
@Alexandru199205 
I see that you have removed the ability to resize the window via mouse resize using the window border, but the maximize button is still there. 

I would remove that as well (see comment from above o how to do it)

**Comment by Alexandru199205** [comment]
Solved, with the maximize button disable the maximize button. @Dorin-Foaltin

**Comment by dorufoaltin** [comment]
I think you misunderstood me, I was proposing to disable the maximize button, so the user doesn't have the ability to maximize the window, by setting **MaximizeBox** property to **false**, like this: 

![image](https://user-images.githubusercontent.com/6756850/132181140-813dbf74-573b-4b80-b52f-558eaf55a0bf.png)

This will disable the maximize button, so the user will not be able to click on it, like this: 

![image](https://user-images.githubusercontent.com/6756850/132181266-66cb8c9d-abbc-4e6b-a812-7dcb434ec67a.png)

**Comment by Alexandru199205** [comment]
I did it and it was like in your screenshot above. Maybe i forgot to push it on git hub.
