### ISSUE TITLE
Stop reusing event handler methods

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#12]
Reusing event handler methods is not a good practice, mostly because the type of senders and event args are different, so even if the code compiles, the sender is: 

- TextBox when called frem keyboard
- Button when called from button click, 

and the event args is 

- KeyPressedEventArgs when called from keyboard 
- MouseEventArgs when called from button click. 

This is not a problem now, but let's say this is a bigger application, and 3 years from now you are asked to change what happens when you click the button with right click instead of left click, then you will use the MouseEventArgs (by casting the EventArgs e variable), and the app will crash on keyboard pressed, since casting KeyPressedEventArgs  to MouseEventArgs  is not possible.

![image](https://user-images.githubusercontent.com/6756850/134346050-51826656-7caa-4cf9-bdb0-5a05a773e386.png)

A better way to do this is to have another method which is called from both locations, something like this: 

![image](https://user-images.githubusercontent.com/6756850/134346868-b4d59193-0f22-48e3-ac7e-1db247127a32.png)

Now we should be able to enable the right click behavior without crashing, something like this: 

![image](https://user-images.githubusercontent.com/6756850/134347231-8c69cae7-968f-49a6-88ef-7b57caf782c3.png)

**Comment by Alexandru199205** [comment]
I Followed the ex above and solved it. @dorufoaltin

**Comment by Dorin-Foaltin** [comment]
Nice! 

One small change I would do: I would rename this method so it is clear what the method is doing, instead of now being clear that it is called when the description is clicked, something like UpdateDescriptionWithFirstValue 

![image](https://user-images.githubusercontent.com/75241559/138224638-9f4a28d0-dbf0-4545-96e9-860bef2ca6c1.png)
