### ISSUE TITLE
Remove duplicate code

### ISSUE THREAD

**Issue by Dorin-Foaltin** [Alexandru199205/CalculatorTest#13]
There is a programming principle called **Don't Repeat Yourself**, or DRY in short, that states each time you have some lines of code that are repeating, you should try and refactor those into a single method, that can be called from multiple places. 

It is recommended to do this, mostly because if a change is needed in those lines of code, you will have to modify only that method, once, instead of modifying those lines in multiple places, where you could easily forget about one place, and introduce a bug. 

You have these lines which are repeating, that can be refactored into a method: 

![image](https://user-images.githubusercontent.com/75241559/135218795-3ad705cb-5df5-441a-896a-77cb20269d02.png)

**Comment by Alexandru199205** [comment]
I have created a method that helps removing the duplicate code as shown above. @Dorin-Foaltin

**Comment by Dorin-Foaltin** [comment]
Nice! That area of 'Preventing the crash if user enter operators on an empty box.' might be included in the shared method as well, but I see there are some slight differences, and might be just an overhead, and I feel like you already got the point of the exercise, so I am ok with it like this.
