### ISSUE TITLE
Replace operation description textbox with a label

### ISSUE THREAD

**Issue by Dorin-Foaltin** [Alexandru199205/CalculatorTest#14]
I see that you added the description label, this is a very nice improvement! 

I would replace this TextBox with a label control. They both have a Text property, that works exactly the same, but the difference is that the label is just displaying a text, as a information to the user, and the textbox is usually used for entering text by the user.

You can add the label by drag and drop from the toolbox:
![image](https://user-images.githubusercontent.com/75241559/135219154-a31cfbb0-9515-489e-8077-df544c092db3.png)

**Comment by Alexandru199205** [comment]
Thanks for idea. I have replaced the textbox with the label.
