### ISSUE TITLE
Remove more duplicated code

### ISSUE THREAD

**Issue by Dorin-Foaltin** [Alexandru199205/CalculatorTest#16]
You already improved this code not to repeat itself and keep it [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), but we can do a bit more, with a slightly complicated solution.

![image](https://user-images.githubusercontent.com/75241559/138228246-fd624cba-dd98-4156-ae41-fbc411c099ea.png)

As you can see all these event handling methods are doing a similar thing, there are only 2 differences:
1. Which button calls this
2. What parameter is sent to NumCheck method

The solution proposed is:
1. Set the same event handler be called for all 0 to 9 buttons. You can do this by going to event tabs and select the same event handler method to all the buttons, let's say **ButtonZero_Click**.

![image](https://user-images.githubusercontent.com/75241559/138229231-be8c9b31-8298-476c-8223-e47614c13052.png)

2. Once you have all the buttons calling the same event handler, we need to know which button has called that method, you can do that by casting the sender parameter to  the button, something like this:  

![image](https://user-images.githubusercontent.com/75241559/138229572-e868c5ff-7855-422c-ad03-f9584042d5f0.png) 

3. Call the NumCheck method, and pass the button.Tag value as the parameter. Tag is just a property that exists on all controls in winforms, and it exists only for devs to use it, for setting a value specific to that control (button in our case), that can be used in a generic method. 

Something like this: 

![image](https://user-images.githubusercontent.com/75241559/138229728-2ba3f8d8-c52e-46e6-b07d-644459581cc8.png)

4. Set the tag value for each button, something like this: 

![image](https://user-images.githubusercontent.com/75241559/138230461-63aef651-b439-407e-a038-eb5d04750ee9.png)

5. Rename ButtonZeroClick to something like NumberButtonClick to better specify to inform other devs better on what the method is actually doing

**Comment by Alexandru199205** [comment]
Solved as explained above. Nice and smooth way @Dorin-Foaltin
