### ISSUE TITLE
Modulo operator. Wrong output above the input field.

### ISSUE THREAD

**Issue by AndreiBacescu** [Alexandru199205/CalculatorTest#17]
![image](https://user-images.githubusercontent.com/17107914/140803358-101b119c-e384-4460-99f3-cb8f3c6260bc.png)

Steps to reproduce:
1) press any number
2) press modulo operator 

Expected result:
I would expect to see 0 instead of "0%".

**Comment by Alexandru199205** [comment]
Thanks for tip. solved it @AndreiBacescu
