### ISSUE TITLE
Calcul cu litere 

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#2]
User-ul nu ar trebui sa poata sa introduca litere, pentru asta poti sa faci **TextBox-ul readonly**: 

![image](https://user-images.githubusercontent.com/6756850/130405220-0b8d8591-4d46-4d3e-a2a7-e656c13ffc64.png)

![image](https://user-images.githubusercontent.com/6756850/130405507-79970c19-d5e3-4b83-8ec6-1fd99a29286e.png)

**Comment by Alexandru199205** [comment]
Solved this as presented above
