### ISSUE TITLE
Divide By Zero Exception

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#3]
Incearca sa rezolvi toate cazurile de exceptie, e unul din cele mai bune moduri sa inveti ca lumea. Aplicatia nu ar trebui sa crape niciodata, orice i-ai face. 

Am incercat 7 / 0, si evident ca crapa: 

![image](https://user-images.githubusercontent.com/6756850/130405909-bb3e3e9c-5608-4091-bd2d-a26b4ef44cd6.png)

**Comment by Dorin-Foaltin** [comment]
@Alexandru199205 : I see this is fixed. Let's do the following from now on: 

Once issue is fixed by you: 
1. Close the issue (there should be a button to close it near the comment button)
2. Add comment, and state how this is fixed, and tag me, so I receive a notification and I can check

**Comment by Alexandru199205** [comment]
I will do so from now on.  Thanks

joi, 2 sept. 2021, 10:38 Dorin Foaltin ***@***.***> a scris:
