### ISSUE TITLE
Refactor multiple ifs to switch statement

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#9]
Every time you see a lot of if () if() if() if(), you should try to use switch statement, because switch is easier to read for other programmers. 

So these: 
![image](https://user-images.githubusercontent.com/6756850/134343309-b9a63838-80ee-48a4-808c-5e6724614513.png)

Would look something like this:
![image](https://user-images.githubusercontent.com/6756850/134343254-ce14758d-eab7-4820-aae8-653018699c98.png)

**Comment by Dorin-Foaltin** [comment]
I think you forgot to push some code, because in the latest changes this is still using ifs not switch: 

![image](https://user-images.githubusercontent.com/75241559/135217721-4f394a8b-aa8f-47fc-950e-a901521e6e8c.png)
